### ISSUE TITLE
WordPress database table prefix (feature request)

### ISSUE THREAD

**Issue by christianwach** [sgladstone/com.pogstone.contenttokens#1]
I notice that you're querying the WordPress database directly and making assumptions about the table name prefix - namely that it is always the default "wp_". This is a user choice on installation and you'll find that your queries fail if someone chooses a different prefix. It's more common than you might think.

Is there a situation where this extension's code will run when WordPress is not bootstrapped? If not, then I recommend using the WordPress API (or the global `$wpdb`) to query the database. If yes, then alternative methods will be needed to determine the table name prefix. I may be able to help either way.

Cheers, Christian

**Comment by sgladstone** [comment]
Christian - I updated the extension to dynamically get the database schema for the WordPress tables. ( ie they no longer have to be in the same database as the CiviCRM tables.)  Make sure you pull "Master"  or version 2.7.      The extension will only run AFTER WordPress and CiviCRM is bootstrapped.   Can you provide sample code of getting the WordPress prefix?

**Comment by christianwach** [comment]
Hi, good to see that the WP DB is being extracted from 'civicrm.settings.php' via `$config`. That'll allow it to work on more systems.

I'm struggling to see where the extension makes sure WordPress is bootstrapped. Can you be sure that token replacement only happens when CiviCRM and WordPress are bootstrapped? I can imagine that a cron job might be the source of the process when a mail is sent - in that case, I suspect only CiviCRM would be bootstrapped.

If you do know that WordPress is bootstrapped, then the `$wpdb` global has all the info you need. The prefix is `$wpdb->prefix` for example, the posts table is `$wpdb->posts` - and so on. However, if you have access to `$wpdb` then WordPress is bootstrapped, so you may as well use `get_posts()`!

I'm working on an update to Civi's WordPress plugin such that it stores some of the essential WordPress constants - because at present there's no predictable and reliable way of getting them from the outside. This should help you situation... but not immediately, I'm afraid.

**Comment by totten** [comment]
I don't think it's the extension's responsibility to bootstrap anything -- the extension consumes a hook. Bootstrapping should be handled at the PHP entry-point which runs the cron job. The major entry points are:
- The CMS's index.php (which eventually delegates to CRM_Core_Invoke)
- bin/cli.php (which calls civicrm.config.php and eventually System::loadBootstrap)
- extern/rest.php (which calls civicrm.config.php and eventually System::loadBootstrap)
- bin/cron.php (which calls civicrm.config.php, but as far as I can grep it does not call loadBootstrap)
- drush cvapi (which has built-in support for Drupal bootstrap)
- wp civicrm api (which has built-in support for WP bootstrap)

To be honest -- I didn't even know bin/cron.php existed. Architecturally, the idea is to expose the cron system via API; so one can call the "Job.process" API via any means (bin/cli.php, extern/rest.php, etc). But it looks like the [documentation](http://wiki.civicrm.org/confluence/display/CRMDOC/Managing+Scheduled+Jobs) directs folks to use cron.php, and cron.php is the outlier which (apparently) neglects to bootstrap. IMHO, if bin/cron.php fails to bootstrap the CMS, then that's an integrity bug in cron.php. All the others are doing it right.

**Comment by christianwach** [comment]
Hi @sgladstone I wanted to make you aware of https://github.com/civicrm/civicrm-wordpress/pull/75 which has been merged and allows you (for versions of Civi > 4.6.4, I think) to retrieve the "one true path" to 'wp-load.php' in order to bootstrap WordPress when you need to do. You can get the path by calling:

`$path = CRM_Core_BAO_Setting::getItem('CiviCRM Preferences', 'wpLoadPhp');`

**Comment by sgladstone** [comment]
Per totten's earlier comment, extensions do NOT need to bootstrap the CMS.   FYI: the latest version of this extension has code to dynamically retrieve the Joomla table prefix.  Perhaps you can use this as a mechanism to do the same for the WordPress table prefix. (I do not have a WordPress test environment myself)

**Comment by christianwach** [comment]
Well sure, you can rely on the code upstream to do its job correctly. Or your extension can take responsibility for making sure that it is doing so. I'm not trying to be prescriptive here, just informing you of a way that you can do that if you want to.

Moreover, you can rely on your extension's fragile SQL to retrieve content from WordPress, or you can use the functions that WordPress provides. But if the WordPress database schema changes for any reason, your SQL may break. And more critically, think about what your code will retrieve if the content of the post contains, for example, a shortcode. Let's say a gallery, defined thus: `[gallery ids="729,732,731,720"]`. Instead of WordPress running the content through the `the_content()` filter and returning the gallery HTML, you'll just get the shortcode text.

Anyway, it's up to you how you want to handle this. I've simply tried to make you aware of some non-obvious complexities of interfacing with WordPress.

**Comment by sgladstone** [comment]
I am hoping since the code is on GitHub, a WordPress developer can submit pull requests with the appropriate changes. (Someone from the Joomla community has already done so, and I merged their code in.)
