### ISSUE TITLE
Links in content are being created with incorrect domain

### ISSUE THREAD

**Issue by herbdool** [sgladstone/com.pogstone.contenttokens#4]
I've tested a mailing and the links are being given a domain that is somehow derived from the server path and not from the actual domain of the website. So none of the relative links work.

Line 104 of contenttokens.php:

`$website_host_name = $_SERVER['SERVER_NAME'];`

Might be possible to get the domain from a civicrm.settings.php?

**Comment by herbdool** [comment]
Just for a bit more context, I'm using CiviCRM on Pantheon and the SERVER_NAME appears as `endpoint302395758844.chios.panth.io` for example.

**Comment by sgladstone** [comment]
I updated the master of this project to fix this problem. Can you verify that this works for you? If so I will package a new version of the extension

**Comment by sgladstone** [comment]
I also updated the master branch for my other extension that had the same issue (https://github.com/sgladstone/com.pogstone.fancytokens)
