### ISSUE TITLE
Joomla: wrong db prefix

### ISSUE THREAD

**Issue by lsmithgo** [sgladstone/com.pogstone.contenttokens#6]
I had a problem with Civicrm crashing (CRM-001 error) as soon as I installed this extension on Joomla.  Error was that my 'content' table didn't exist but the query had derived the wrong DB Prefix.

For the moment, I have forced the right answer by hardcoding it in line 636 of 'contenttokens.php'.

It would appear that userFrameworkUsersTableName is not set right in my database, despite everything else working

**Comment by sgladstone** [comment]
What is the value for "userFrameworkUsersTableName" in your environment?

Also, Is there a Joomla API or SQL statement that could be used to determine your Joomla database prefix?
