### ISSUE TITLE
DB Error: no such table

### ISSUE THREAD

**Issue by Buzzbee1** [sgladstone/com.pogstone.contenttokens#7]
We run CIVICRM 4.6.17 with Drupal 7. After installing your very useful extension (which I would really like to use), and try to either start a new mailing or edit an existing mailing, I get the error. Once I disable your extension, everything works fine again. I have searched the internet and there was a similar problem with an Alpha version of 4.6. However, it was resolved. Could you please point me to what could be missing?
Many thanks in advance!

**Comment by sgladstone** [comment]
Can you provide a screen print of the error? And a stack trace? (Make sure your CiviCRM settings at http://yourdomain.com/civicrm/admin/setting/debug?reset=1   have "yes" for the questions "Enable Debugging" and "Display Backtrace" )
